apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backend
  - ./release-update
images:
  - name: devozs/weather-app
    newTag: 0.0.6 # {"$imagepolicy": "flux-system:weather-app:tag"}
