apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system

resources:
  - weather-app-image-repository.yaml
  - weather-app-image-policy.yaml
  - image-update-automation.yaml
