apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  selector:
    matchLabels:
      run: weather-app
  replicas: 1
  template:
    metadata:
      labels:
        run: weather-app
    spec:
      containers:
        - name: weather-app
          image: devozs/weather-app:latest

